### ISSUE TITLE
Replace multiple mat files at once

### ISSUE THREAD

**Issue by HeilanMo** [smlu/ProjectMarduk#2]
Hey, is it somehow possible to replace multiple mat files at once.  I would like to replace all textures from the first level but the cnd file has 162 textures and I can only replace them one by one. Is it for example possible to add a complete folder with the mat files to the cnd?

**Comment by smlu** [comment]
Hey, yes it's possible to replace multiple mat files in one go. 
You should be able to execute  the command `cndtool add material --replace` on multiple `*.mat` files. 
e.g.:
```
cndtool.exe add material --replace some_level.cnd mat1.mat mat2.mat mat3.mat mat4.mat
```

*Side note: I'm upgrading `cndtool` to convert CND to NDY file format. When it's finished you won't need to patch CND files anymore.*

**Comment by HeilanMo** [comment]
Hey thank you it worked. Now it is a lot easier to change textures for me. I'm experementing a bit with texture upscaling at the moment. 
![Screenshot (2)](https://user-images.githubusercontent.com/68738336/88547649-50b72e80-d01e-11ea-9182-7a564bccdb66.png)
![Screenshot (6)](https://user-images.githubusercontent.com/68738336/88547676-5745a600-d01e-11ea-96ef-c9d4868db6ac.png)

So I'm looking forward to see your next version of cndtool. It will be much easier to replace the textures when you don't have to patch the cnd files

**Comment by smlu** [comment]
@HeilanMo that's great to hear. Btw I'm in contact with someone who's doing the HD texture upscale too. If you want to get in touch with him please PM through [gog.com](https://www.gog.com/forum).
