### ISSUE TITLE
.wav files

### ISSUE THREAD

**Issue by TheRenegadist** [smlu/ProjectMarduk#4]
So I was able to use your tools to extract various .wav files from the game but they don't appear to be in a readable format, any suggestions on getting them normalized to work as other .wav files do?

**Comment by frasercow** [comment]
The .wav files that are used by the game are in indywv format, so they are unplayable without conversion. CND tool has the ability to convert the sounds to a playable .wav format by using this command when extracting the contents of the CND file cndtool extract --sound-wav --no-key --no-mat <path_to_cnd_file>

If you're looking to start modding the game you can follow this tutorial.
https://github.com/Jones3D-The-Infernal-Engine/Documentation/blob/main/pre-mod.md

Feel free to Join the Jones3D Community on Discord
https://discord.gg/NX9E8mWp
